/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'var(--m3-bg)',
        surface: 'var(--m3-surface)',
        'surface-container': 'var(--m3-surface-container)',
        'surface-high': 'var(--m3-surface-container-high)',
        'surface-highest': 'var(--m3-surface-container-highest)',
        'surface-dim': 'var(--m3-surface-dim)',
        'surface-bright': 'var(--m3-surface-bright)',
        'surface-tint': 'var(--m3-surface-tint)',
        primary: 'var(--m3-primary)',
        'primary-container': 'var(--m3-primary-container)',
        'on-primary': 'var(--m3-on-primary)',
        'on-primary-container': 'var(--m3-on-primary-container)',
        secondary: 'var(--m3-secondary)',
        'secondary-container': 'var(--m3-secondary-container)',
        'on-secondary': 'var(--m3-on-secondary)',
        'on-secondary-container': 'var(--m3-on-secondary-container)',
        tertiary: 'var(--m3-tertiary)',
        'tertiary-container': 'var(--m3-tertiary-container)',
        'on-tertiary-container': 'var(--m3-on-tertiary-container)',
        success: 'var(--m3-success)',
        'success-container': 'var(--m3-success-container)',
        danger: 'var(--m3-danger)',
        'danger-container': 'var(--m3-danger-container)',
        warning: 'var(--m3-warning)',
        'warning-container': 'var(--m3-warning-container)',
        'text-primary': 'var(--m3-on-surface)',
        'text-secondary': 'var(--m3-on-surface-variant)',
        'text-tertiary': 'var(--m3-outline)',
        outline: 'var(--m3-outline)',
        'outline-variant': 'var(--m3-outline-variant)',
      },
      borderRadius: {
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '28px',
        xl: '32px',
        '2xl': '40px',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        'elevation-1': 'var(--m3-elevation-1)',
        'elevation-2': 'var(--m3-elevation-2)',
        'elevation-3': 'var(--m3-elevation-3)',
        'elevation-4': 'var(--m3-elevation-4)',
      },
      transitionTimingFunction: {
        spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'spring-gentle': 'cubic-bezier(0.22, 1.2, 0.36, 1)',
        emphasized: 'cubic-bezier(0.2, 0, 0, 1)',
      },
      fontSize: {
        'display-lg': ['40px', { lineHeight: '1.1', fontWeight: '900' }],
        'display': ['32px', { lineHeight: '1.1', fontWeight: '800' }],
        'headline-lg': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline': ['22px', { lineHeight: '1.2', fontWeight: '700' }],
        'title-lg': ['20px', { lineHeight: '1.3', fontWeight: '600' }],
        'title': ['16px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '1.4', fontWeight: '600' }],
        'label': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
        'caption': ['11px', { lineHeight: '1.3', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
